const {chromium}=require('playwright-core'),fs=require('node:fs');
(async()=>{const browser=await chromium.launch({executablePath:process.env.CHROME_PATH||'C:/Program Files/Google/Chrome/Application/chrome.exe',headless:true});try{
 fs.mkdirSync('public/social',{recursive:true});fs.mkdirSync('public/icons',{recursive:true});
 const page=await browser.newPage({viewport:{width:1200,height:630},deviceScaleFactor:1});await page.goto('http://127.0.0.1:5188/');await page.waitForFunction(()=>window.rexChase?.rex,{timeout:120000});
 await page.evaluate(async()=>{const r=rexChase;r.freeze=true;const s={phase:'pursuit',phaseTime:0,distance:10.5,health:5600};for(let i=0;i<80;i++)r.rex.update(1/60,s,i/60,10,{jaw:.78,roar:.35});r.jeep.root.visible=true;r.state.transition('pursuit');for(let i=0;i<60;i++)r.jeep.update(1/60,i/60,10,r.rex.headPosition(),false,r.state);r.camera.position.set(.06,2.4,-.45);r.camera.lookAt(3,3.3,9);r.camera.fov=51;r.camera.updateProjectionMatrix();r.rex.gaze.update(1,r.camera.position);r.renderer.render(r.scene,r.camera);await document.fonts.ready;});
 await page.addStyleTag({content:`body>*:not(canvas):not(#social-card){display:none!important}#social-card{position:fixed;inset:0;z-index:20;background:linear-gradient(90deg,#07110df5 0%,#0c170ee8 30%,#0d180f66 56%,transparent 78%),linear-gradient(0deg,#08100bd9,transparent 40%);font-family:'DM Sans',Arial,sans-serif;color:#f0efdd;padding:54px 60px;box-sizing:border-box}#social-card .kicker{font-size:12px;letter-spacing:3px;color:#e8be75;font-weight:700}#social-card .title{font-family:'Barlow Condensed',Impact,sans-serif;font-weight:800;font-size:119px;line-height:.88;letter-spacing:1px;margin:33px 0 23px}#social-card .title span{color:#e8be75}#social-card .hook{font-size:25px;line-height:1.4;letter-spacing:-.5px;font-weight:600;margin:0}#social-card .play{position:absolute;left:60px;bottom:59px;padding:17px 22px;background:#e8be75;color:#142014;font-size:12px;letter-spacing:1.8px;font-weight:800}#social-card .caption{position:absolute;right:45px;bottom:31px;font-size:10px;letter-spacing:2px;color:#e2e8d1b0}#social-card .rule{position:absolute;left:60px;top:37px;width:42px;height:3px;background:#e8be75}`});
 await page.evaluate(()=>{const c=document.createElement('div');c.id='social-card';c.innerHTML='<i class="rule"></i><div class="kicker">FREE BROWSER GAME</div><div class="title">REX:<br><span>PURSUIT</span></div><p class="hook">90 seconds. One Jeep.<br>No second chances.</p><div class="play">SURVIVE THE CHASE &nbsp; ↗</div><div class="caption">IN-GAME CAPTURE</div>';document.body.append(c);});
 await page.screenshot({path:'public/social/rex-pursuit-v1.jpg',type:'jpeg',quality:91});
 // Raster app icons come from the project's vector mark, not an external asset.
 const svg=fs.readFileSync('public/favicon.svg','utf8');
 await page.setContent(`<style>html,body{margin:0;background:#131c15}svg{display:block;width:100vw;height:100vh}</style>${svg}`);
 for(const [size,name]of [[32,'icon-32'],[180,'apple-touch-icon'],[192,'icon-192'],[512,'icon-512']]){await page.setViewportSize({width:size,height:size});await page.screenshot({path:`public/icons/${name}.png`});}
 console.log('Created 1200x630 in-game share card and app icons.');
 }finally{await browser.close();}})().catch(e=>{console.error(e);process.exit(1);});
