const {chromium}=require('playwright-core');const fs=require('fs');const path=require('path');
const dir='audio_reference',source=fs.readdirSync(dir).find(f=>f.endsWith('.mp3'));
function wav(samples,rate){const b=Buffer.alloc(44+samples.length*2);b.write('RIFF');b.writeUInt32LE(b.length-8,4);b.write('WAVEfmt ',8);b.writeUInt32LE(16,16);b.writeUInt16LE(1,20);b.writeUInt16LE(1,22);b.writeUInt32LE(rate,24);b.writeUInt32LE(rate*2,28);b.writeUInt16LE(2,32);b.writeUInt16LE(16,34);b.write('data',36);b.writeUInt32LE(samples.length*2,40);for(let i=0;i<samples.length;i++)b.writeInt16LE(Math.max(-32768,Math.min(32767,Math.round(samples[i]*32767))),44+i*2);return b;}
(async()=>{const browser=await chromium.launch({executablePath:'C:/Program Files/Google/Chrome/Application/chrome.exe',headless:true});try{const p=await browser.newPage();const result=await p.evaluate(async encoded=>{const raw=Uint8Array.from(atob(encoded),c=>c.charCodeAt(0));const ctx=new OfflineAudioContext(1,1,24000);const input=await ctx.decodeAudioData(raw.buffer);const offline=new OfflineAudioContext(1,Math.ceil(input.duration*24000),24000);const src=offline.createBufferSource();src.buffer=input;src.connect(offline.destination);src.start();const output=await offline.startRendering();const a=output.getChannelData(0),hop=480;const envelope=[];for(let i=0;i<a.length;i+=hop){let sum=0,peak=0;for(let k=i;k<Math.min(i+hop,a.length);k++){sum+=a[k]*a[k];peak=Math.max(peak,Math.abs(a[k]));}envelope.push({t:i/24000,rms:Math.sqrt(sum/hop),peak});}return {duration:input.duration,rate:24000,envelope,samples:Array.from(a)};},fs.readFileSync(path.join(dir,source)).toString('base64'));
 const max=Math.max(...result.envelope.map(x=>x.rms)),threshold=Math.max(.006,max*.035);let start=null,lastLoud=0;const spans=[];
 for(const e of result.envelope){if(e.rms>threshold){if(start===null)start=Math.max(0,e.t-.12);lastLoud=e.t;}else if(start!==null&&e.t-lastLoud>.42){if(lastLoud-start>.32)spans.push([start,Math.min(result.duration,lastLoud+.2)]);start=null;}}
 if(start!==null)spans.push([start,result.duration]);
 fs.mkdirSync(path.join(dir,'clips'),{recursive:true});fs.mkdirSync('public/audio',{recursive:true});
 const clips=spans.map(([start,end],i)=>{const samples=result.samples.slice(Math.floor(start*result.rate),Math.ceil(end*result.rate));const peak=Math.max(...result.envelope.filter(e=>e.t>=start&&e.t<end).map(e=>e.peak));const gain=Math.min(2,.86/Math.max(.01,peak));for(let j=0;j<samples.length;j++){const edge=Math.min(1,j/240,(samples.length-1-j)/480);samples[j]*=gain*Math.max(0,edge);}const filename=`clip-${String(i+1).padStart(2,'0')}.wav`;fs.writeFileSync(path.join(dir,'clips',filename),wav(samples,result.rate));return {id:i+1,file:filename,start:+start.toFixed(2),end:+end.toFixed(2),duration:+(end-start).toFixed(2),peak:+peak.toFixed(3),label:''};});
 fs.writeFileSync(path.join(dir,'clips','catalog.json'),JSON.stringify({source,duration:result.duration,threshold,clips},null,2));
 const lines=clips.map(c=>`${c.id}\t${c.start}\t${c.end}\t${c.duration}\t${c.peak}`);console.log(`Source ${result.duration.toFixed(2)}s; ${clips.length} separated clips\nID\tSTART\tEND\tLENGTH\tPEAK\n`+lines.join('\n'));
 const bars=result.envelope.filter((_,i)=>i%5===0).map(e=>`<line x1="${e.t/result.duration*1400}" x2="${e.t/result.duration*1400}" y1="${140-e.rms/max*110}" y2="${140+e.rms/max*110}" stroke="#b0b871"/>`).join('');const labels=clips.map(c=>`<text x="${c.start/result.duration*1400}" y="${30+c.id%2*18}" fill="#fff" font-size="11">${c.id}</text>`).join('');fs.writeFileSync(path.join(dir,'clips','waveform.svg'),`<svg xmlns="http://www.w3.org/2000/svg" width="1400" height="280"><rect width="1400" height="280" fill="#16231d"/>${bars}${labels}</svg>`);
 }finally{await browser.close();}})().catch(e=>{console.error(e);process.exit(1)});
