import assert from 'node:assert/strict';
import {BREACH,BreachRound,waveAt} from '../src/breach/rules.js';
const advance=(r,seconds,act=()=>{})=>{for(let t=0;t<seconds-1e-8;t+=1/60){act(r);r.tick(Math.min(1/60,seconds-t));}};
assert.deepEqual([0,3,37,40,72,75,94].map(waveAt),[0,1,0,2,0,3,4]);
const r=new BreachRound();
assert.equal(r.startReload(),false);assert.equal(r.hitRex(100),false);
assert.equal(r.shoot(),true);assert.equal(r.shoot(),false);assert.equal(r.ammo,79);
assert.equal(r.startReload(),true);assert.equal(r.shoot(),false);
advance(r,3);assert.equal(r.ammo,80);assert.equal(r.reload,0);
const before=JSON.stringify(r);r.tick(0);assert.equal(JSON.stringify(r),before,'Zero simulation time leaves cooldowns and events frozen');
assert.equal(r.discharge(),true);assert.equal(r.discharge(),false);
assert.equal(r.launchGrenade(),true);assert.equal(r.launchGrenade(),false);
advance(r,18.1);assert.equal(r.discharge(),true);assert.equal(r.launchGrenade(),true);
r.reset();r.killed();r.killed({trap:true});r.killed({onJeep:true});
assert.deepEqual([r.kills,r.trapKills,r.saves,r.score],[3,1,1,400]);
r.damage(14);assert.equal(r.jeep,86);r.damage(100);assert.equal(r.result,'lost');
const lost=JSON.stringify(r);advance(r,150);r.shoot();r.killed();r.hitRex(99);assert.equal(JSON.stringify(r),lost,'Defeat is terminal');
r.reset();advance(r,117);assert.equal(r.result,'lost','Ignoring the Rex loses before the exit opens');
assert.equal(r.drain().filter(e=>e.type==='lost')[0].source,'rex');
r.reset();advance(r,99.1);const d=r.rexDistance;
for(let i=0;i<13;i++)assert.equal(r.hitRex(),false);
assert.equal(r.hitRex(),true);assert.ok(r.rexDistance>d);assert.equal(r.staggers,1);
advance(r,25,round=>{if(round.time>=99&&round.rexDistance<22)round.hitRex(BREACH.staggerHits);});
assert.equal(r.result,'won');assert.equal(r.phase,'escape');assert.equal(r.gate,1);assert.ok(r.score>=2000);
const events=r.drain();for(const name of ['reveal','breach','gate','escape','won'])assert.equal(events.filter(e=>e.type===name).length,1,`${name} happens once`);
const won=JSON.stringify(r);advance(r,100);assert.equal(JSON.stringify(r),won);
r.reset();assert.deepEqual([r.time,r.result,r.jeep,r.ammo,r.kills,r.score,r.trap,r.grenade],[0,null,100,80,0,0,0,0]);
// Continuous firing eventually reloads and cannot bypass the heat/fire-rate limits.
advance(r,25,round=>round.shoot());assert.ok(r.shots>80&&r.shots<25/BREACH.fireInterval);assert.ok(r.ammo>=0&&r.heat<=1);
console.log('Breach rules passed: waves, fire/heat/reload, trap/grenade cooldowns, scoring, pause, Rex pressure/stagger, escape, terminal outcomes and reset.');
