const {chromium}=require('playwright-core'),assert=require('node:assert/strict'),fs=require('node:fs'),path=require('node:path'),http=require('node:http');
const mime={'.html':'text/html','.js':'text/javascript','.css':'text/css','.jpg':'image/jpeg','.png':'image/png','.svg':'image/svg+xml','.json':'application/json','.webmanifest':'application/manifest+json','.wasm':'application/wasm','.wav':'audio/wav','.glb':'model/gltf-binary','.xml':'application/xml','.txt':'text/plain'};
(async()=>{let server;const local=!process.env.TEST_URL,dist=path.resolve('dist');
 if(local){server=http.createServer((req,res)=>{try{let pathname=new URL(req.url,'http://localhost').pathname;if(!pathname.startsWith('/rex-pursuit/'))throw Error('Outside Pages base');let relative=decodeURIComponent(pathname.slice('/rex-pursuit/'.length))||'index.html';const file=path.resolve(dist,relative);if(!file.startsWith(dist+path.sep))throw Error('Outside build');res.setHeader('Content-Type',mime[path.extname(file)]||'application/octet-stream');res.end(fs.readFileSync(file));}catch{res.writeHead(404);res.end('Not found');}});await new Promise(resolve=>server.listen(5189,'127.0.0.1',resolve));}
 const base=process.env.TEST_URL||'http://127.0.0.1:5189/rex-pursuit/',browser=await chromium.launch({executablePath:process.env.CHROME_PATH||'C:/Program Files/Google/Chrome/Application/chrome.exe',headless:true});
 try{
  const errors=[],page=await browser.newPage({viewport:{width:1440,height:900}});page.on('pageerror',e=>errors.push(e.message));page.on('console',m=>{if(m.type()==='error')errors.push(m.text());});page.on('response',r=>{if(r.status()>=400&&r.url().startsWith(new URL(base).origin))errors.push(`${r.status()} ${r.url()}`);});
  await page.goto(base);await page.waitForFunction(()=>window.rexChase?.rex,{timeout:120000});assert.match(await page.title(),/^Rex: Pursuit/);
  const card=await page.evaluate(async()=>{const src=document.querySelector('[property="og:image"]').content;const img=new Image();img.src='./social/rex-pursuit-v1.jpg';await img.decode();return{url:src,width:img.naturalWidth,height:img.naturalHeight};});assert.equal(card.width,1200);assert.equal(card.height,630);
  await page.screenshot({path:`art/review/pages-${local?'local':'live'}-menu.png`});await page.locator('#start').click();await page.waitForFunction(()=>rexChase.mode==='playing');await page.waitForFunction(()=>{const a=rexChase.audio;return a.ready&&[...Object.values(a.roles),3,4,5,6,9,18,27,11,12,14,30,31].every(n=>a.buffers.has(n));},null,{timeout:60000});
  await page.evaluate(()=>{rexChase.state.transition('pursuit');rexChase.state.distance=15;rexChase.state.nextDebris=Infinity;});await page.waitForTimeout(500);await page.keyboard.press('v');await page.waitForTimeout(300);assert.equal(await page.evaluate(()=>rexChase.view),'third');await page.keyboard.press('p');assert.equal(await page.evaluate(()=>rexChase.mode),'paused');await page.locator('#resume').click();assert.equal(await page.evaluate(()=>rexChase.mode),'playing');
  await page.goto(new URL('sound-library.html',base).href);await page.waitForSelector('.clip');assert.equal(await page.locator('.clip').count(),34);
  const audioFailures=await page.evaluate(async()=>{const failures=[];for(let i=1;i<=34;i++){const r=await fetch(`./audio/clip-${String(i).padStart(2,'0')}.wav`,{cache:'no-store'});if(!r.ok)failures.push({url:r.url,status:r.status});await r.arrayBuffer();}return failures;});assert.deepEqual(audioFailures,[],'Every published audio file is available');
  await page.goto(new URL('model-lab.html',base).href);await page.waitForFunction(()=>window.rexStudy,{timeout:120000});
  const phone=await browser.newPage({viewport:{width:390,height:844},isMobile:true,hasTouch:true});phone.on('pageerror',e=>errors.push(e.message));await phone.goto(base);await phone.waitForFunction(()=>window.rexChase?.rex,{timeout:120000});assert.equal(await phone.evaluate(()=>document.documentElement.scrollWidth>innerWidth),false);await phone.locator('#start').click();await phone.waitForFunction(()=>rexChase.mode==='playing');await phone.screenshot({path:`art/review/pages-${local?'local':'live'}-phone.png`});await phone.close();assert.deepEqual(errors,[]);
  console.log(`Pages passed at ${base}: game, all 34 sounds, camera/pause, lab, phone layout and 1200x630 share card. No runtime or asset errors.`);
 }finally{await browser.close();if(server)await new Promise(resolve=>server.close(resolve));}
})().catch(e=>{console.error(e);process.exit(1);});
