const {chromium}=require('playwright-core');const assert=require('node:assert/strict');const fs=require('fs');
const base=process.env.TEST_URL||'http://127.0.0.1:5188/';
(async()=>{const browser=await chromium.launch({executablePath:'C:/Program Files/Google/Chrome/Application/chrome.exe',headless:true});const errors=[],results=[];const page=await browser.newPage({viewport:{width:1600,height:1000},deviceScaleFactor:1});const watch=p=>{p.on('pageerror',e=>errors.push(e.message));p.on('console',m=>{if(m.type()==='error')errors.push(m.text());});p.on('response',r=>{if(r.status()>=400&&r.url().startsWith(base))errors.push(`${r.status()} ${r.url()}`);});};watch(page);
 await page.goto(base);await page.waitForFunction(()=>window.rexChase?.rex,{timeout:120000});await page.screenshot({path:'art/review/chase-menu.png'});await page.locator('#start').click();await page.waitForFunction(()=>rexChase.mode==='playing');await page.waitForTimeout(1000);assert.ok(await page.evaluate(()=>[1,2,3,4,5,6,9,18,27,11,12,14,30,31].every(n=>rexChase.audio.buffers.has(n))));assert.equal(await page.evaluate(()=>rexChase.audio.context.state),'running');await page.screenshot({path:'art/review/chase-opening.png'});
 await page.evaluate(()=>{rexChase.state.phase='pursuit';rexChase.state.phaseTime=0;rexChase.state.distance=17;rexChase.state.nextDebris=Infinity;});await page.waitForTimeout(700);
 const aimHead=()=>page.evaluate(async()=>{const r=rexChase,mesh=r.rex.skin,p=mesh.geometry.attributes.position;let best=Infinity,index=0;for(let i=0;i<p.count;i++){const dist=(p.getX(i)-.15)**2+(p.getY(i)-4.35)**2+(p.getZ(i)-6.65)**2;if(dist<best){best=dist;index=i;}}const point=r.camera.position.clone();mesh.getVertexPosition(index,point);mesh.localToWorld(point);const projected=point.project(r.camera);return{x:(projected.x*.5+.5)*innerWidth,y:(-projected.y*.5+.5)*innerHeight,index};});
 const aim=await aimHead();await page.mouse.move(aim.x,aim.y);await page.mouse.down();await page.waitForTimeout(700);await page.mouse.up();const shotStats=await page.evaluate(()=>rexChase.snapshot());assert.ok(shotStats.health<5600,'Raycast bullets must damage the animal');assert.ok(shotStats.wounds>0,'Impacts must leave surface wounds');assert.ok(shotStats.headshots>0,'Snout hits must count as headshots');assert.ok(shotStats.ammo<80);results.push({shotStats});
 const ammo=shotStats.ammo;await page.keyboard.press('r');assert.ok(await page.evaluate(()=>rexChase.state.reload>0));await page.mouse.down();await page.waitForTimeout(300);await page.mouse.up();assert.equal(await page.evaluate(()=>rexChase.state.ammo),ammo);await page.waitForFunction(()=>rexChase.state.reload===0);assert.equal(await page.evaluate(()=>rexChase.state.ammo),80);
 const head=await aimHead();await page.mouse.move(head.x,head.y);await page.keyboard.press('Space');assert.ok(await page.evaluate(()=>rexChase.state.grenade>8));assert.ok(await page.evaluate(()=>rexChase.rex.damage.points.some(p=>p.w<0)),'Explosive must leave a scorch wound');await page.waitForTimeout(1700);await page.screenshot({path:'art/review/chase-first.png'});
 await page.keyboard.press('Escape');assert.equal(await page.evaluate(()=>rexChase.mode),'paused');const before=await page.evaluate(()=>rexChase.state.time);await page.waitForTimeout(300);assert.equal(await page.evaluate(()=>rexChase.state.time),before);await page.locator('#resume').click();await page.keyboard.press('v');await page.waitForTimeout(750);assert.equal(await page.evaluate(()=>rexChase.view),'third');await page.screenshot({path:'art/review/chase-third.png'});
 await page.evaluate(()=>{rexChase.state.phase='bite';rexChase.state.phaseTime=.7;rexChase.state.distance=11.5;});await page.waitForFunction(()=>rexChase.state.jeep<100);assert.equal(await page.evaluate(()=>rexChase.state.jeep),73);await page.screenshot({path:'art/review/chase-impact.png'});
 await page.keyboard.press('v');await page.evaluate(()=>{rexChase.state.phase='charge';rexChase.state.phaseTime=0;rexChase.state.distance=12.4;rexChase.state.stagger=9;rexChase.state.shotTimer=0;rexChase.state.overheated=false;});const closeHead=await aimHead();await page.mouse.move(closeHead.x,closeHead.y);await page.mouse.down();await page.waitForTimeout(130);await page.mouse.up();assert.equal(await page.evaluate(()=>rexChase.state.interrupts),1);await page.screenshot({path:'art/review/chase-head-damage.png'});
 const gait=await page.evaluate(()=>{rexChase.freeze=true;const r=rexChase,legs=['L','R'].map(s=>r.rex.bones.find(b=>b.name.startsWith(`foot_02_04_${s}_end`)));r.rex.gait.reset();const frames=[];for(let i=0;i<60;i++){r.rex.update(1/60,{phase:'pursuit',distance:18,phaseTime:0,result:null},i/60);frames.push(legs.map(b=>b.getWorldPosition(r.camera.position.clone()).toArray()));}r.freeze=false;return frames;});const spread=gait.map(v=>v[0][1]-v[1][1]);assert.ok(Math.max(...spread)>.3&&Math.min(...spread)<-.3,'Run must alternate planted and raised feet');assert.ok(gait.flat().every(p=>p.every(Number.isFinite)),'IK must remain finite');results.push({gaitMinY:Math.min(...gait.flat().map(p=>p[1])),gaitMaxY:Math.max(...gait.flat().map(p=>p[1]))});
 await page.evaluate(()=>{rexChase.state.health=10;rexChase.state.hit(true);});await page.waitForFunction(()=>rexChase.mode==='ended',{timeout:15000});assert.match(await page.locator('#end-title').textContent(),/made it/);await page.locator('#restart').click();await page.waitForFunction(()=>rexChase.mode==='playing');assert.equal(await page.evaluate(()=>rexChase.rex.damage.count),0);assert.equal(await page.evaluate(()=>rexChase.state.health),5600);await page.evaluate(()=>{rexChase.state.jeep=10;rexChase.state.phase='bite';rexChase.state.phaseTime=.8;});await page.waitForFunction(()=>rexChase.mode==='ended',{timeout:15000});assert.match(await page.locator('#end-title').textContent(),/Too close/);results.push(await page.evaluate(()=>rexChase.snapshot()));
 await page.goto(new URL('sound-library.html',base).href);await page.waitForSelector('.clip');assert.equal(await page.locator('.clip').count(),34);await page.getByLabel('Name clip 01').fill('Opening roar QA');await page.locator('#opening').selectOption('34');await page.reload();await page.waitForSelector('.clip');assert.equal(await page.getByLabel('Name clip 01').inputValue(),'Opening roar QA');assert.equal(await page.locator('#opening').inputValue(),'34');await page.locator('audio').first().evaluate(a=>a.play());await page.waitForFunction(()=>document.querySelector('audio').currentTime>0);const download=page.waitForEvent('download');await page.locator('#export').click();assert.equal((await download).suggestedFilename(),'rex-sound-catalog.json');await page.screenshot({path:'art/review/sound-library.png'});await page.evaluate(()=>localStorage.removeItem('rex-pursuit-audio-v1'));
 for(const [name,width,height]of [['phone',390,844],['small-phone',390,680],['landscape',844,390]]){const p=await browser.newPage({viewport:{width,height},deviceScaleFactor:1,isMobile:true,hasTouch:true});watch(p);await p.goto(base);await p.waitForFunction(()=>window.rexChase?.rex,{timeout:120000});await p.screenshot({path:`art/review/chase-${name}-menu.png`});await p.locator('#start').click();await p.waitForFunction(()=>rexChase.mode==='playing');await p.evaluate(()=>{rexChase.state.phase='pursuit';rexChase.state.distance=18;});await p.waitForTimeout(600);const layout=await p.evaluate(()=>({overflow:document.documentElement.scrollWidth>innerWidth,buttons:[...document.querySelectorAll('#hud-bottom button,#touch-controls button,#sound,#pause')].filter(b=>getComputedStyle(b).display!=='none').map(b=>{const r=b.getBoundingClientRect();return {name:b.textContent,x:r.x,y:r.y,right:r.right,bottom:r.bottom};})}));assert.equal(layout.overflow,false);for(const b of layout.buttons)assert.ok(b.x>=0&&b.y>=0&&b.right<=width+1&&b.bottom<=height+1,`${name}: clipped ${JSON.stringify(b)}`);await p.locator('#touch-fire').dispatchEvent('pointerdown',{pointerId:1,pointerType:'touch'});await p.waitForTimeout(200);await p.locator('#touch-fire').dispatchEvent('pointerup',{pointerId:1,pointerType:'touch'});assert.ok(await p.evaluate(()=>rexChase.state.ammo<80));await p.screenshot({path:`art/review/chase-${name}.png`});results.push({name,layout});await p.close();}
 assert.deepEqual(errors,[]);fs.writeFileSync('art/review/chase-verification.json',JSON.stringify({errors,results},null,2));console.log(JSON.stringify({errors,results},null,2));await browser.close();})().catch(e=>{console.error(e);process.exit(1)});
