const {chromium}=require('playwright-core');
const assert=require('node:assert/strict');
const fs=require('node:fs');
const base=process.env.TEST_URL||'http://127.0.0.1:5188/';
const publicUrl='https://vibecodingmatt.github.io/rex-pursuit/';
(async()=>{
 fs.mkdirSync('art/review',{recursive:true});
 const browser=await chromium.launch({executablePath:process.env.CHROME_PATH||'C:/Program Files/Google/Chrome/Application/chrome.exe',headless:true});
 const errors=[],report=[];
 const monitor=p=>{p.on('pageerror',e=>{errors.push(e.message);console.error(e);});p.on('console',m=>{if(m.type()==='error'){errors.push(m.text());console.error(m.text());}});p.on('response',r=>{if(r.status()>=400)errors.push(`${r.status()} ${r.url()}`);});};
 async function load(p){monitor(p);await p.goto(base);await p.waitForFunction(()=>window.rexChase?.rex,null,{timeout:120000});await p.locator('#start').click();await p.waitForFunction(()=>rexChase.mode==='playing');}
 async function win(p,view='first',distance=19){await p.evaluate(({view,distance})=>{const r=rexChase,s=r.state;r.setView(view);s.transition('pursuit');s.distance=distance;s.nextDebris=Infinity;s.fightTime=42;s.objectivesCleared=3;s.debrisCleared=2;},{view,distance});await p.waitForTimeout(350);await p.evaluate(()=>rexChase.state.damage(5600));await p.waitForFunction(()=>rexChase.state.victory?.time>0);}
 const snapshot=()=>{const r=rexChase;return {time:r.state.victory.time,waterTime:r.visitorCenter.pond.water.material.uniforms.time.value,mode:r.mode,view:r.view,jeep:r.jeep.root.position.toArray(),camera:r.camera.position.toArray(),black:+document.querySelector('#fatal-black').style.opacity,arrival:r.visitorCenter.root.visible,death:r.rex.death.complete,fightTime:r.state.fightTime,stats:[r.state.objectivesCleared,r.state.debrisCleared]};};
 async function capture(p,t,name){await p.waitForFunction(t=>rexChase.state.victory?.time>=t,t,{timeout:60000});await p.evaluate(()=>rexChase.freeze=true);const s=await p.evaluate(snapshot);await p.screenshot({path:`art/review/victory-${name}.png`});await p.evaluate(()=>rexChase.freeze=false);report.push({name,...s});return s;}
 async function paused(p){await p.keyboard.press('p');const before=await p.evaluate(snapshot);assert.equal(await p.evaluate(()=>rexChase.audio.context.state),'suspended');await p.waitForTimeout(300);assert.deepEqual(await p.evaluate(snapshot),before);await p.keyboard.press('p');}
 async function buttonsFit(p){await p.waitForFunction(()=>+getComputedStyle(document.querySelector('#end-screen .modal-card')).opacity===1);const boxes=await p.evaluate(()=>['restart','share-game','copy-game-link'].map(id=>{const b=document.getElementById(id).getBoundingClientRect();return{id,visible:b.width>0&&b.height>0,inViewport:b.left>=0&&b.top>=0&&b.right<=innerWidth&&b.bottom<=innerHeight};}));assert.ok(boxes.every(b=>b.visible&&b.inViewport),JSON.stringify(boxes));assert.equal(await p.evaluate(()=>document.documentElement.scrollWidth>innerWidth),false);}
 try{
  const p=await browser.newPage({viewport:{width:1440,height:900}});await load(p);await win(p);
  await capture(p,2,'fall');await capture(p,5.7,'pullback');assert.equal(await p.locator('#end-screen').isVisible(),false);await paused(p);await p.keyboard.press('v');assert.equal(await p.evaluate(()=>rexChase.view),'third');assert.equal(await p.evaluate(()=>rexChase.shoot()),false);
  const dark=await capture(p,7.05,'cut');assert.equal(dark.black,1);assert.equal(dark.arrival,false);
  await capture(p,9.5,'approach');await capture(p,13,'drive');await paused(p);
  const parked=await capture(p,17,'parked');assert.ok(parked.arrival&&parked.death);assert.ok(Math.abs(parked.jeep[0])<1e-6&&parked.jeep[1]===0&&parked.jeep[2]===-53);assert.equal(parked.black,0);
  await capture(p,18.8,'fade');await p.waitForFunction(()=>rexChase.mode==='ended',null,{timeout:60000});assert.equal(await p.locator('#end-title').textContent(),'You made it.');assert.equal(await p.evaluate(()=>+document.querySelector('#fatal-black').style.opacity),1);assert.ok((await p.locator('#end-stats').textContent()).includes('3 attacks repelled'));await buttonsFit(p);await p.screenshot({path:'art/review/victory-results-desktop.png'});
  // Native share, dismissed sheet, unavailable sheet and clipboard/manual fallbacks.
  await p.evaluate(()=>{window.shared=[];Object.defineProperty(navigator,'share',{configurable:true,writable:true,value:async data=>{window.shared.push(data);}});});await p.locator('#share-game').focus();await p.keyboard.press('Space');const shared=await p.evaluate(()=>window.shared);assert.equal(shared[0].url,publicUrl);assert.match(shared[0].text,/Visitor Center/);assert.equal(shared[0].title,'Rex: Pursuit');
  await p.evaluate(()=>{navigator.share=async()=>{throw new DOMException('Dismissed','AbortError')};document.querySelector('#share-status').textContent='';});await p.locator('#share-game').click();assert.equal(await p.locator('#share-status').textContent(),'');assert.equal(await p.locator('#share-fallback').isVisible(),false);
  await p.evaluate(()=>navigator.share=async()=>{throw new DOMException('Unavailable','NotAllowedError')});await p.locator('#share-game').click();assert.equal(await p.locator('#share-fallback').isVisible(),true);
  await p.evaluate(()=>{Object.defineProperty(navigator,'clipboard',{configurable:true,value:{writeText:async value=>{window.copied=value;}}});});await p.locator('#copy-game-link').click();assert.equal(await p.evaluate(()=>window.copied),publicUrl);assert.match(await p.locator('#share-status').textContent(),/Link copied/);
  await p.evaluate(()=>{navigator.share=undefined;navigator.clipboard.writeText=async()=>{throw Error('Denied')};});await p.locator('#share-game').click();assert.equal(await p.locator('#share-link').inputValue(),publicUrl);assert.equal(await p.locator('#share-link').evaluate(e=>e.selectionEnd-e.selectionStart),publicUrl.length);
  await p.locator('#restart').click();await p.waitForFunction(()=>rexChase.mode==='playing');assert.equal(await p.evaluate(()=>rexChase.state.victory),null);assert.equal(await p.evaluate(()=>rexChase.visitorCenter.root.visible),false);assert.equal(await p.evaluate(()=>rexChase.rex.death.active),false);assert.equal(await p.evaluate(()=>+document.querySelector('#fatal-black').style.opacity),0);assert.deepEqual(await p.evaluate(()=>rexChase.jeep.root.position.toArray()),[0,0,0]);
  // A real loss still uses the existing defeat, and offers the same sharing UI.
  await p.evaluate(()=>{const s=rexChase.state;s.transition('pursuit');s.distance=19;s.nextDebris=Infinity;});await p.waitForTimeout(300);await p.evaluate(()=>{const s=rexChase.state;s.jeep=1;s.phase='bite';s.phaseTime=.77;});await p.waitForFunction(()=>rexChase.mode==='ended',null,{timeout:60000});await buttonsFit(p);assert.equal(await p.locator('#end-title').textContent(),'Too close.');await p.evaluate(()=>navigator.share=async data=>{window.lossShare=data;});await p.locator('#share-game').click();assert.equal(await p.evaluate(()=>window.lossShare.url),publicUrl);assert.match(await p.evaluate(()=>window.lossShare.text),/caught my Jeep/);await p.screenshot({path:'art/review/victory-share-loss.png'});await p.close();
  for(const [width,height]of [[390,844],[844,390]]){
   const phone=await browser.newPage({viewport:{width,height},isMobile:true,hasTouch:true,reducedMotion:width===390?'reduce':'no-preference'});await load(phone);await win(phone,'third',11);await capture(phone,16.8,`mobile-${width}`);await phone.waitForFunction(()=>rexChase.mode==='ended',null,{timeout:60000});await buttonsFit(phone);await phone.screenshot({path:`art/review/victory-results-${width}.png`});await phone.evaluate(()=>{Object.defineProperty(navigator,'share',{configurable:true,writable:true,value:undefined});Object.defineProperty(navigator,'clipboard',{configurable:true,value:{writeText:async()=>{}}});});await phone.locator('#share-game').tap();assert.match(await phone.locator('#share-status').textContent(),/Link copied/);await phone.locator('#restart').tap();await phone.waitForFunction(()=>rexChase.mode==='playing');assert.equal(await phone.evaluate(()=>rexChase.state.victory),null);await phone.close();
  }
  assert.deepEqual(errors,[]);fs.writeFileSync('art/review/victory-verification.json',JSON.stringify({errors,report},null,2));console.log('Victory fall, arrival, pause, camera lock, fade, stats, restart, win/loss sharing and phone layouts passed.');
 }finally{await browser.close();}
})().catch(e=>{console.error(e);process.exit(1)});
