const {chromium}=require('playwright-core');
const assert=require('node:assert/strict'),fs=require('node:fs');
const base=process.env.TEST_URL||'http://127.0.0.1:5188/';
const guestFrame=()=>{const g=rexChase.swallow.guest;return{visible:g.root.visible,reveal:g.reveal,position:g.guest.position.toArray(),head:g.head.quaternion.toArray(),tie:g.tie.quaternion.toArray(),poolTime:g.pool.material.uniforms.time.value,bubbles:[...g.root.children.find(o=>o.isInstancedMesh).instanceMatrix.array]};};
(async()=>{const browser=await chromium.launch({executablePath:'C:/Program Files/Google/Chrome/Application/chrome.exe',headless:true});const errors=[],report={};
try{
 const p=await browser.newPage({viewport:{width:1600,height:1000}});p.on('pageerror',e=>errors.push(e.message));p.on('console',m=>{if(m.type()==='error')errors.push(m.text());});
 await p.goto(base);await p.waitForFunction(()=>window.rexChase?.rex,{timeout:120000});await p.locator('#start').click();await p.waitForFunction(()=>rexChase.mode==='playing');
 await p.evaluate(()=>{const r=rexChase;r.setView('third');r.state.transition('pursuit');r.state.distance=19;r.state.nextDebris=Infinity;});await p.waitForTimeout(650);
 await p.evaluate(()=>{const s=rexChase.state;s.jeep=1;s.phase='bite';s.phaseTime=.77;});await p.waitForFunction(()=>rexChase.state.result==='lost');assert.equal(await p.evaluate(()=>rexChase.view),'first');
 report.frames=[];
 for(const t of [.9,1.6,1.85,3.2,4.7,6.8,8.6,8.85,9.05,9.2,9.35,9.48,9.6,9.9,10.15,10.6,10.85,11.25,12.5,13.3,13.95,14.25,14.7,14.85,15.05,15.3,15.65]){
  await p.waitForFunction(t=>rexChase.state.defeat?.time>=t,t);await p.evaluate(()=>rexChase.freeze=true);
  report.frames.push(await p.evaluate(()=>{const r=rexChase,m=r.rex.mouthPosition();return{t:r.state.defeat.time,root:r.rex.actor.position.toArray(),jeep:r.jeep.root.position.toArray(),jeepYaw:r.jeep.root.rotation.y,gunDetached:r.jeep.weapon.detached,gunPosition:r.jeep.yaw.position.toArray(),mouth:m.center.toArray(),upper:m.upper.toArray(),lower:m.lower.toArray(),camera:r.camera.position.toArray(),jaw:r.rex.vocal.jaw,interior:r.swallow.active,slide:r.swallow.progress,swallowCue:r.state.defeat.cues.has('swallow'),interiorCamera:r.swallow.camera.position.toArray(),interiorDirection:r.swallow.camera.getWorldDirection(r.camera.position.clone()).toArray(),blood:+document.querySelector('#fatal-blood').style.opacity,black:+document.querySelector('#fatal-black').style.opacity,mode:r.mode,view:r.view};}));
  const guest=await p.evaluate(guestFrame),frame=report.frames[report.frames.length-1];frame.guest={visible:guest.visible,reveal:guest.reveal};Object.assign(frame,await p.evaluate(()=>({immersion:rexChase.swallow.immersion,acidLevel:rexChase.swallow.guest.pool.position.y,splashCue:rexChase.state.defeat.cues.has('splash')})));
  if(t<=12.5||t===15.65)assert.equal(guest.visible,false,'The guest is hidden until the late descent and after blackout');
  if(t===13.95){assert.ok(guest.visible&&guest.reveal>.99);assert.ok(await p.evaluate(()=>rexChase.state.defeat.cues.has('digest')));}
  await p.screenshot({path:`art/review/defeat-${String(t).replace('.','-')}.png`});await p.evaluate(()=>rexChase.freeze=false);
  if(t===13.3){await p.keyboard.press('p');await p.waitForFunction(()=>rexChase.audio.context.state==='suspended');const heldGuest=await p.evaluate(guestFrame);await p.waitForTimeout(250);assert.deepEqual(await p.evaluate(guestFrame),heldGuest,'Body, tie, lighting, liquid and bubbles freeze with Pause');await p.keyboard.press('p');}
  if(t===14.7||t===15.05){await p.keyboard.press('p');await p.waitForFunction(()=>rexChase.audio.context.state==='suspended');const plungeFrame=()=>({t:rexChase.state.defeat.time,camera:rexChase.swallow.camera.position.toArray(),rotation:rexChase.swallow.camera.quaternion.toArray(),immersion:rexChase.swallow.immersion,black:document.querySelector('#fatal-black').style.opacity,pool:rexChase.swallow.guest.pool.material.uniforms.time.value}),held=await p.evaluate(plungeFrame);await p.waitForTimeout(250);assert.deepEqual(await p.evaluate(plungeFrame),held,'Plunge, immersion and impact fade pause with audio');await p.keyboard.press('p');}
  if(t===3.2){await p.keyboard.press('p');const frozen=await p.evaluate(()=>({t:rexChase.state.defeat.time,gun:rexChase.jeep.yaw.position.toArray(),spin:rexChase.jeep.root.rotation.y,black:document.querySelector('#fatal-black').style.opacity}));await p.waitForTimeout(250);assert.deepEqual(await p.evaluate(()=>({t:rexChase.state.defeat.time,gun:rexChase.jeep.yaw.position.toArray(),spin:rexChase.jeep.root.rotation.y,black:document.querySelector('#fatal-black').style.opacity})),frozen);await p.keyboard.press('p');await p.keyboard.press('v');assert.equal(await p.evaluate(()=>rexChase.view),'first');assert.equal(await p.evaluate(()=>rexChase.shoot()),false);}
  if(t===10.15||t===12.5){await p.keyboard.press('p');const frozen=await p.evaluate(()=>({t:rexChase.state.defeat.time,slide:rexChase.swallow.progress,camera:rexChase.swallow.camera.position.toArray(),audio:rexChase.audio.context.state}));assert.equal(frozen.audio,'suspended');await p.waitForTimeout(250);assert.deepEqual(await p.evaluate(()=>({t:rexChase.state.defeat.time,slide:rexChase.swallow.progress,camera:rexChase.swallow.camera.position.toArray(),audio:rexChase.audio.context.state})),frozen);await p.keyboard.press('p');}
 }
 assert.ok(report.frames.filter(f=>f.t<1.65).every(f=>!f.gunDetached));assert.ok(report.frames.filter(f=>f.t>1.85).every(f=>f.gunDetached));assert.ok(report.frames.filter(f=>f.t>4.7).every(f=>Math.abs(f.jeepYaw-2*Math.PI)<1e-6),'Jeep completes exactly one revolution before the final approach');for(let i=1;i<report.frames.length;i++)assert.ok(report.frames[i].jeepYaw>=report.frames[i-1].jeepYaw,'The spin never reverses');
 const stare=report.frames.find(f=>f.t>=8.6),windup=report.frames.find(f=>f.t>=9.2),gulp=report.frames.find(f=>f.t>=9.48);
 const interior=report.frames.filter(f=>f.t>=10&&f.t<13.9);assert.ok(interior.every(f=>f.interior&&f.blood===0&&f.black===0),'Visible interior replaces the red flash before the fade');
 const hold=report.frames.filter(f=>f.t>=9.9&&f.t<10.8),lift=report.frames.find(f=>f.t>=10.85),descent=report.frames.find(f=>f.t>=12.5),arrival=report.frames.find(f=>f.t>=13.95);
 assert.ok(hold.length>=3&&hold.every(f=>f.slide===0&&!f.swallowCue),'No slide or swallowing sound during the mouth hold');for(const f of hold)assert.deepEqual(f.interiorCamera,hold[0].interiorCamera,'The player is held in place inside the mouth');
 assert.ok(lift.upper[1]>hold[0].upper[1]+.5,'The Rex raises her head after capturing the player');assert.ok(lift.interiorDirection[1]>hold[0].interiorDirection[1]+.15,'The interior view tips with the head before the slide');
 assert.ok(descent.slide>.35&&descent.slide<.7&&descent.swallowCue,'Slower descent is still underway after the head lift');assert.ok(arrival.interiorCamera[2]>hold[0].interiorCamera[2]+10,'Camera eventually reaches the wider chamber');
 const plungeFrames=report.frames.filter(f=>f.t>=13.3&&f.t<15.6);
 for(let i=1;i<plungeFrames.length;i++)assert.ok(plungeFrames[i].interiorCamera[1]<plungeFrames[i-1].interiorCamera[1]-.025,'The camera continues falling through the chamber');
 for(const f of plungeFrames){if(f.t<15){assert.equal(f.black,0,'No fade before acid contact');assert.equal(f.immersion,0);assert.equal(f.splashCue,false);assert.ok(f.interiorCamera[1]>f.acidLevel);}else{assert.ok(f.interiorCamera[1]<f.acidLevel&&f.interiorDirection[1]<-.85,'Camera enters the acid face first');assert.ok(f.immersion>0&&f.black>0&&f.black<1&&f.splashCue,'Splash, immersion and fade begin after contact');}}
 assert.ok(stare.jaw<.05,'Jaw stays relaxed for the look at the player');assert.ok(windup.upper[1]>stare.upper[1]+.15,'The head visibly lifts back before the gulp');assert.ok(gulp.root[2]<windup.root[2]-2,'The final bite surges forward');assert.ok(Math.abs(stare.camera[1]-windup.camera[1])<.025,'The camera must not follow and cancel out the head-back motion');
 await p.waitForFunction(()=>rexChase.mode==='ended');assert.equal(await p.evaluate(()=>+document.querySelector('#fatal-black').style.opacity),1);assert.equal(await p.locator('#end-title').textContent(),'Too close.');await p.screenshot({path:'art/review/defeat-ended.png'});
 for(const reason of ['ram','debris','timeout']){
  await p.evaluate(()=>rexChase.start());await p.evaluate(reason=>{const r=rexChase,s=r.state;r.setView('third');s.transition('pursuit');s.phaseTime=0;s.distance=reason==='debris'?22:11;s.nextDebris=Infinity;
   if(reason==='timeout')s.fightTime=89.99;
   else if(reason==='ram'){s.jeep=1;s.attackNumber=1;s.phase='ram';s.phaseTime=.77;}
   else{s.jeep=1;s.spawnDebris();while(s.debris.status==='attached')s.tickDebris(1/60);s.debris.age=s.debris.duration-.01;}
  },reason);
  await p.waitForFunction(()=>rexChase.state.defeat?.time>.1);assert.equal(await p.evaluate(()=>rexChase.view),'first');assert.equal(await p.evaluate(()=>rexChase.jeep.gunner.visible),false);assert.equal(await p.evaluate(()=>+document.querySelector('#fatal-black').style.opacity),0);
  await p.waitForFunction(()=>rexChase.mode==='ended');assert.equal(await p.evaluate(()=>+document.querySelector('#fatal-black').style.opacity),1);
 }
 await p.evaluate(()=>rexChase.start());assert.equal(await p.evaluate(()=>rexChase.state.defeat),null);assert.equal(await p.evaluate(()=>rexChase.swallow.active),false);assert.equal(await p.evaluate(()=>rexChase.swallow.immersion),0);assert.equal(await p.evaluate(()=>rexChase.swallow.guest.root.visible),false);assert.equal(await p.evaluate(()=>+document.querySelector('#fatal-black').style.opacity),0);assert.ok(await p.evaluate(()=>!rexChase.jeep.weapon.detached&&rexChase.jeep.yaw.parent===rexChase.jeep.body&&rexChase.jeep.weapon.hands.visible&&rexChase.jeep.root.rotation.y===0));
 await p.close();report.mobile=[];
 for(const [width,height]of [[390,844],[844,390]]){
  const phone=await browser.newPage({viewport:{width,height},isMobile:true,hasTouch:true});phone.on('pageerror',e=>errors.push(e.message));phone.on('console',m=>{if(m.type()==='error')errors.push(m.text());});
  await phone.goto(base);await phone.waitForFunction(()=>window.rexChase?.rex,{timeout:120000});await phone.locator('#start').click();await phone.evaluate(()=>{const r=rexChase;r.setView('third');r.state.transition('pursuit');r.state.distance=19;r.state.nextDebris=Infinity;});await phone.waitForTimeout(500);
  await phone.evaluate(()=>{const s=rexChase.state;s.jeep=1;s.phase='bite';s.phaseTime=.77;});await phone.waitForFunction(()=>rexChase.state.defeat?.time>=9.50);await phone.evaluate(()=>rexChase.freeze=true);
  const frame=await phone.evaluate(()=>{const r=rexChase,c=r.rex.mouthPosition().center.project(r.camera);return{view:r.view,mouthNdc:c.toArray(),overflow:document.documentElement.scrollWidth>innerWidth};});assert.equal(frame.view,'first');assert.equal(frame.overflow,false);assert.ok(Math.abs(frame.mouthNdc[0])<.4&&Math.abs(frame.mouthNdc[1])<.6,'The mouth must enclose the mobile camera');report.mobile.push({width,height,...frame});await phone.screenshot({path:`art/review/defeat-mobile-${width}.png`});await phone.evaluate(()=>rexChase.freeze=false);
  await phone.waitForFunction(()=>rexChase.state.defeat?.time>=10.05);await phone.evaluate(()=>rexChase.freeze=true);assert.equal(await phone.evaluate(()=>rexChase.swallow.progress),0);await phone.screenshot({path:`art/review/defeat-mobile-${width}-hold.png`});await phone.evaluate(()=>rexChase.freeze=false);
  await phone.waitForFunction(()=>rexChase.state.defeat?.time>=12.5);await phone.evaluate(()=>rexChase.freeze=true);assert.equal(await phone.evaluate(()=>rexChase.swallow.active),true);await phone.screenshot({path:`art/review/defeat-mobile-${width}-throat.png`});await phone.evaluate(()=>rexChase.freeze=false);
  await phone.waitForFunction(()=>rexChase.state.defeat?.time>=13.95);await phone.evaluate(()=>rexChase.freeze=true);
  const cameo=await phone.evaluate(()=>{const r=rexChase,g=r.swallow.guest,head=g.head.getWorldPosition(r.camera.position.clone()).project(r.swallow.camera);return{visible:g.root.visible,reveal:g.reveal,head:head.toArray()};});assert.ok(cameo.visible&&cameo.reveal>.99&&Math.abs(cameo.head[0])<.55&&Math.abs(cameo.head[1])<.7,'The lawyer face stays in the phone frame');
  await phone.screenshot({path:`art/review/defeat-mobile-${width}-guest.png`});await phone.evaluate(()=>rexChase.freeze=false);
  for(const t of [14.85,15.1]){await phone.waitForFunction(t=>rexChase.state.defeat?.time>=t,t);await phone.evaluate(()=>rexChase.freeze=true);const impact=await phone.evaluate(()=>({y:rexChase.swallow.camera.position.y,level:rexChase.swallow.guest.pool.position.y,black:+document.querySelector('#fatal-black').style.opacity,immersion:rexChase.swallow.immersion,splash:rexChase.state.defeat.cues.has('splash')}));if(t<15){assert.ok(impact.y>impact.level&&impact.black===0&&impact.immersion===0&&!impact.splash);}else assert.ok(impact.y<impact.level&&impact.black>0&&impact.black<1&&impact.immersion>.6&&impact.splash);await phone.screenshot({path:`art/review/defeat-mobile-${width}-${t<15?'acid-approach':'acid-impact'}.png`});await phone.evaluate(()=>rexChase.freeze=false);}
  await phone.waitForFunction(()=>rexChase.mode==='ended');const end=await phone.evaluate(()=>{const overlay=document.querySelector('#fatal-black'),b=document.querySelector('#restart').getBoundingClientRect();return{black:+overlay.style.opacity,overlay:[overlay.clientWidth,overlay.clientHeight],button:[b.left,b.top,b.right,b.bottom]};});assert.equal(end.black,1);assert.deepEqual(end.overlay,[width,height]);assert.ok(end.button[0]>=0&&end.button[1]>=0&&end.button[2]<=width&&end.button[3]<=height,'Retry remains accessible');await phone.screenshot({path:`art/review/defeat-mobile-${width}-ended.png`});await phone.locator('#restart').click();await phone.waitForFunction(()=>rexChase.mode==='playing');assert.equal(await phone.evaluate(()=>rexChase.state.defeat),null);await phone.close();
 }
 assert.deepEqual(errors,[]);fs.writeFileSync('art/review/defeat-verification.json',JSON.stringify({errors,...report},null,2));console.log(JSON.stringify({errors,...report},null,2));
}finally{await browser.close();}})().catch(e=>{console.error(e);process.exit(1)});
