const {chromium}=require('playwright-core'),assert=require('node:assert/strict'),fs=require('node:fs');
const base=process.env.TEST_URL||'http://127.0.0.1:5188/';
(async()=>{const browser=await chromium.launch({executablePath:process.env.CHROME_PATH||'C:/Program Files/Google/Chrome/Application/chrome.exe',headless:true}),report=[],errors=[];try{
 for(const [name,width,height]of [['phone',390,844],['small-phone',320,568],['landscape',844,390],['tablet',768,1024]]){
  const page=await browser.newPage({viewport:{width,height},isMobile:true,hasTouch:true});page.on('pageerror',e=>errors.push(e.message));page.on('console',m=>{if(m.type()==='error')errors.push(m.text());});
  const cdp=await page.context().newCDPSession(page),send=(type,points=[])=>cdp.send('Input.dispatchTouchEvent',{type,touchPoints:points.map(p=>({radiusX:14,radiusY:14,force:1,...p}))});
  await page.goto(base);await page.waitForFunction(()=>window.rexChase?.rex,null,{timeout:120000});await page.locator('#start').tap();await page.waitForFunction(()=>rexChase.mode==='playing');
  const prepare=()=>page.evaluate(()=>{const s=rexChase.state;s.transition('pursuit');s.phaseTime=-100;s.fightTime=0;s.nextDebris=Infinity;s.ambushPlayed=true;s.distance=15;s.ammo=80;s.heat=0;s.overheated=false;s.reload=0;s.shotTimer=0;});await prepare();await page.waitForTimeout(450);
  const layout=await page.evaluate(()=>({overflow:document.documentElement.scrollWidth>innerWidth,buttons:[...document.querySelectorAll('#touch-controls button,#hud-bottom button,.header-right button')].filter(b=>b.getClientRects().length&&getComputedStyle(b).display!=='none').map(b=>{const r=b.getBoundingClientRect(),s=getComputedStyle(b);return{id:b.id||b.textContent.trim(),x:r.x,y:r.y,w:r.width,h:r.height,selection:s.userSelect,touch:s.touchAction};})}));
  assert.equal(layout.overflow,false);for(const b of layout.buttons){assert.ok(b.x>=0&&b.y>=0&&b.x+b.w<=width+1&&b.y+b.h<=height+1,`${name}: clipped ${b.id}`);assert.ok(b.w>=44&&b.h>=44,`${name}: small tap area ${b.id}`);assert.equal(b.selection,'none');}
  await page.evaluate(()=>{window.touchTrace=[];for(const type of ['pointerdown','pointerup','pointercancel','lostpointercapture'])document.addEventListener(type,e=>touchTrace.push({type,id:e.pointerId,target:e.target.id}));});
  const button=layout.buttons.find(b=>b.id==='touch-fire'),fire={id:2,x:button.x+button.w/2,y:button.y+button.h/2},offset=height<width?72:96;
  const reticle=()=>page.evaluate(()=>{const r=document.querySelector('#reticle').getBoundingClientRect();return{x:r.x+r.width/2,y:r.y+r.height/2};});
  let aim={id:1,x:width*.32,y:height*.53};await send('touchStart',[aim]);let at=await reticle();assert.ok(Math.abs(at.x-aim.x)<1&&Math.abs(at.y-(aim.y-offset))<1,'Reticle is above the thumb');
  await send('touchStart',[aim,fire]);await page.waitForTimeout(220);const fired=await page.evaluate(()=>rexChase.state.ammo);assert.ok(fired<80,'Trusted touch fires the weapon');
  aim={...aim,x:aim.x+20,y:aim.y-18};await send('touchMove',[aim,fire]);at=await reticle();assert.ok(Math.abs(at.x-aim.x)<1&&Math.abs(at.y-(aim.y-offset))<1);
  await send('touchEnd',[aim]);await page.waitForTimeout(220);assert.ok(await page.evaluate(()=>rexChase.state.ammo)<fired,'Lifting the aim thumb must not stop fire');assert.equal(await page.locator('#touch-fire').evaluate(b=>b.classList.contains('pressed')),true,JSON.stringify(await page.evaluate(()=>touchTrace)));
  await send('touchStart',[aim,fire]);await send('touchEnd',[fire]);const released=await page.evaluate(()=>rexChase.state.ammo);await page.waitForTimeout(180);assert.equal(await page.evaluate(()=>rexChase.state.ammo),released,'Lifting fire leaves aim active without firing');assert.equal(await page.locator('#touch-contact').isVisible(),true);
  await page.screenshot({path:`art/review/touch-${name}.png`});await send('touchEnd',[]);
  // Holding a real touch must not start text selection or a copy/paste menu.
  await prepare();await send('touchStart',[fire]);await page.waitForTimeout(850);assert.equal(await page.evaluate(()=>String(getSelection())), '');
  const blocked=await page.locator('#touch-fire').evaluate(b=>{const events=['contextmenu','selectstart'].map(type=>{const e=new Event(type,{bubbles:true,cancelable:true});b.dispatchEvent(e);return e.defaultPrevented;});return{events,touch:getComputedStyle(b).touchAction};});assert.deepEqual(blocked.events,[true,true]);assert.equal(blocked.touch,'none');
  await send('touchCancel',[]);const cancelled=await page.evaluate(()=>rexChase.state.ammo);await page.waitForTimeout(180);assert.equal(await page.evaluate(()=>rexChase.state.ammo),cancelled);assert.equal(await page.locator('#touch-fire').evaluate(b=>b.classList.contains('pressed')),false);
  // The open space in the control row passes through to the aiming canvas.
  const gap=await page.evaluate(()=>{const reload=document.querySelector('#touch-reload').getBoundingClientRect(),y=reload.top+reload.height/2;const [a,b]=[...document.querySelectorAll('#touch-controls button')].map(e=>e.getBoundingClientRect()).filter(r=>r.top<=y&&r.bottom>=y).sort((a,b)=>a.left-b.left);const x=(a.right+b.left)/2;return{x,y,id:document.elementFromPoint(x,y)?.id};});assert.equal(gap.id,'scene');
  if(name==='phone'){
   await prepare();await page.waitForTimeout(250);
   const head=await page.evaluate(()=>{const r=rexChase,m=r.rex.skin,p=m.geometry.attributes.position;let best=Infinity,index=0;for(let i=0;i<p.count;i++){const d=(p.getX(i)-.15)**2+(p.getY(i)-4.35)**2+(p.getZ(i)-6.65)**2;if(d<best){best=d;index=i;}}const v=r.camera.position.clone();m.getVertexPosition(index,v);m.localToWorld(v);v.project(r.camera);return{x:(v.x*.5+.5)*innerWidth,y:(.5-v.y*.5)*innerHeight};});
   aim={id:1,x:head.x,y:head.y+offset};await send('touchStart',[aim]);await send('touchStart',[aim,fire]);await page.waitForTimeout(250);await send('touchEnd',[]);assert.ok(await page.evaluate(()=>rexChase.state.health)<5600,'Bullets land at the lifted reticle');
   await page.locator('#touch-reload').tap();assert.ok(await page.evaluate(()=>rexChase.state.reload)>0);assert.match(await page.locator('#touch-reload small').textContent(),/s$/);await page.locator('#touch-grenade').tap();assert.ok(await page.evaluate(()=>rexChase.state.grenade)>9,'Grenade is reachable during reload');
   await prepare();await page.evaluate(()=>{document.querySelector('#touch-fire').addEventListener('pointerdown',e=>window.touchTestId=e.pointerId);});await send('touchStart',[fire]);await send('touchMove',[{...fire,x:fire.x+1}]);await page.waitForTimeout(120);await page.evaluate(()=>document.querySelector('#touch-fire').releasePointerCapture(window.touchTestId));await send('touchMove',[{...fire,x:fire.x+2}]);await page.waitForTimeout(80);assert.equal(await page.locator('#touch-fire').evaluate(b=>b.classList.contains('pressed')),false,JSON.stringify(await page.evaluate(()=>({id:window.touchTestId,trace:touchTrace.slice(-12),capture:document.querySelector('#touch-fire').hasPointerCapture(window.touchTestId)}))));await send('touchEnd',[]);
   await send('touchStart',[fire]);await page.locator('#pause').evaluate(b=>b.click());assert.equal(await page.evaluate(()=>rexChase.mode),'paused');assert.equal(await page.locator('#touch-fire').evaluate(b=>b.classList.contains('pressed')),false);await send('touchEnd',[]);await page.locator('#resume').tap();const pausedAmmo=await page.evaluate(()=>rexChase.state.ammo);await page.waitForTimeout(150);assert.equal(await page.evaluate(()=>rexChase.state.ammo),pausedAmmo,'Resume never restores an old fire hold');
   await send('touchStart',[fire]);await page.setViewportSize({width:844,height:390});await page.waitForTimeout(120);assert.equal(await page.locator('#touch-fire').evaluate(b=>b.classList.contains('pressed')),false,'Rotation clears held input');await send('touchEnd',[]);await page.setViewportSize({width,height});await page.evaluate(()=>window.dispatchEvent(new Event('blur')));assert.equal(await page.evaluate(()=>rexChase.mode),'paused');await page.locator('#resume').tap();
  }
  await page.locator('#pause').tap();await page.locator('#pause-screen [data-camera="third"]').tap();assert.equal(await page.evaluate(()=>rexChase.view),'third');await page.locator('#resume').tap();assert.equal(await page.evaluate(()=>rexChase.mode),'playing');
  report.push({name,offset,layout,multitouch:true,longPress:true,cancel:true,pauseCamera:true,gap});await page.close();
 }
 assert.deepEqual(errors,[]);fs.writeFileSync('art/review/touch-verification.json',JSON.stringify({errors,report},null,2));console.log('Touch passed on phone, small phone, landscape and tablet: trusted two-thumb input, visible reticle offset, aimed hits, hold/release/cancel, long-press prevention, reload/HE, pause/rotation and 44px controls.');
 }finally{await browser.close();}})().catch(e=>{console.error(e);process.exit(1);});
