const {chromium}=require('playwright-core');const assert=require('node:assert/strict');const fs=require('node:fs');
const base=process.env.TEST_URL||'http://127.0.0.1:5188/',url=new URL('ravine.html',base).href,out='art/review/ravine';fs.mkdirSync(out,{recursive:true});
(async()=>{
 const browser=await chromium.launch({executablePath:process.env.CHROME_PATH||'C:/Program Files/Google/Chrome/Application/chrome.exe',headless:true}),errors=[];
 const watch=p=>{p.on('pageerror',e=>errors.push(e.message));p.on('console',m=>{if(m.type()==='error')errors.push(m.text());});p.on('response',r=>{if(r.status()>=400)errors.push(`${r.status()} ${r.url()}`);});};
 const ready=p=>p.waitForFunction(()=>window.ravine?.ready,null,{timeout:120000});
 try{
  const p=await browser.newPage({viewport:{width:1440,height:900}});watch(p);await p.addInitScript(()=>localStorage.setItem('rex-pursuit-quality','high'));await p.goto(url);await ready(p);assert.equal(await p.locator('#start').isDisabled(),false,'fresh chapter is open for play-testing');assert.equal(await p.evaluate(()=>localStorage.getItem('rex-pursuit-campaign-v1')),null,'open access leaves earned progress alone');await p.locator('#start').click();await p.waitForFunction(()=>ravine.mode==='playing');
  await p.goto(base);await p.waitForFunction(()=>window.rexChase?.mode==='menu',null,{timeout:120000});await p.locator('#start').click();await p.waitForFunction(()=>rexChase.mode==='playing');await p.evaluate(()=>{const s=rexChase.state;s.transition('pursuit');s.nextDebris=Infinity;s.health=10;s.hit(true);});
  await p.waitForFunction(()=>rexChase.mode==='ended',null,{timeout:60000});assert.equal(await p.locator('#next-chapter').isVisible(),true);assert.equal(await p.evaluate(()=>JSON.parse(localStorage.getItem('rex-pursuit-campaign-v1')).ravine),true);await p.screenshot({path:`${out}/chapter-unlocked.png`});
  await p.locator('#next-chapter').click();await ready(p);await p.waitForFunction(()=>ravine.mode==='playing');assert.ok(!p.url().includes('continue='),'one-use continuation consumed');
  // Actual mouse fire against an animated hit target, then pause both clocks.
  await p.evaluate(()=>{ravine.freeze=true;for(let n=0;n<700;n++)ravine.step(1/60);});
  const target=await p.evaluate(()=>{const a=ravine.pack.pool.find(a=>a.root.visible&&a.data.phase==='warn'),v=a.head.clone().project(ravine.camera);return{x:(v.x*.5+.5)*innerWidth,y:(.5-v.y*.5)*innerHeight,id:a.id,hp:a.data.hp};});
  await p.mouse.move(target.x,target.y);await p.mouse.down();await p.evaluate(()=>ravine.step(.02));await p.mouse.up();assert.ok(await p.evaluate(id=>ravine.round.attackers.find(a=>a.id===id).hp<150,target.id));
  await p.keyboard.press('Escape');const held=await p.evaluate(()=>JSON.stringify({t:ravine.round.time,road:ravine.world.travel,actors:ravine.pack.pool.filter(a=>a.root.visible).map(a=>a.root.matrix.toArray())}));await p.evaluate(()=>ravine.step(1));assert.equal(await p.evaluate(()=>JSON.stringify({t:ravine.round.time,road:ravine.world.travel,actors:ravine.pack.pool.filter(a=>a.root.visible).map(a=>a.root.matrix.toArray())})),held);await p.locator('#resume').click();
  await p.screenshot({path:`${out}/desktop-chase.png`});
  await p.keyboard.press('v');await p.evaluate(()=>{for(let n=0;n<45;n++)ravine.step(1/60);});assert.equal(await p.evaluate(()=>ravine.view),'third');await p.screenshot({path:`${out}/desktop-third.png`});
  // Real rays and normal fire rate through a complete fair run. Screenshots
  // sample the viaduct, last pack and extraction gate, not only the start menu.
  await p.evaluate(()=>ravine.start());
  const defend=async seconds=>p.evaluate(seconds=>{const r=ravine;for(let n=0;n<seconds*60&&r.mode==='playing';n++){r.step(1/60);const a=r.pack.pool.filter(a=>a.root.visible&&!['dead','retreat'].includes(a.data.phase)).sort((a,b)=>a.data.z-b.data.z)[0];if(a){r.aimAt(a.head);r.shoot();}}return r.snapshot();},seconds);
  await defend(35);await p.screenshot({path:`${out}/viaduct.png`});await defend(35);await p.screenshot({path:`${out}/north-pass.png`});await defend(19);await p.screenshot({path:`${out}/gate-closing.png`});await defend(6);await p.evaluate(()=>{for(let n=0;n<110;n++)ravine.step(1/60);});assert.equal(await p.evaluate(()=>ravine.round.result),'won');assert.equal(await p.evaluate(()=>ravine.mode),'ended');assert.equal(await p.evaluate(()=>JSON.parse(localStorage.getItem('rex-pursuit-campaign-v1')).completed),true);assert.ok(await p.evaluate(()=>JSON.parse(localStorage.getItem('rex-ravine-scores-v1')).length>0));await p.screenshot({path:`${out}/victory.png`});
  await p.locator('#restart').click();await p.waitForFunction(()=>ravine.mode==='playing');assert.equal(await p.evaluate(()=>ravine.round.ammo),80);assert.equal(await p.evaluate(()=>ravine.round.kills),0);await p.keyboard.type('idkfaidspispipd');assert.equal(await p.evaluate(()=>ravine.round.infiniteAmmo&&ravine.round.infiniteRockets),true);await p.keyboard.type('idkfaidspispipd');assert.equal(await p.evaluate(()=>ravine.round.cheated&&!ravine.round.infiniteAmmo&&!ravine.round.infiniteRockets),true);
  await p.evaluate(()=>{for(let n=0;n<5400&&ravine.mode!=='ended';n++)ravine.step(1/60);});assert.equal(await p.evaluate(()=>ravine.round.result),'lost');assert.equal(await p.evaluate(()=>ravine.mode),'ended');await p.screenshot({path:`${out}/defeat.png`});
  await p.reload();await ready(p);assert.equal(await p.evaluate(()=>ravine.mode),'menu');assert.equal(await p.locator('#start').isDisabled(),false);await p.screenshot({path:`${out}/menu-desktop.png`});
  const ctx=await browser.newContext({viewport:{width:390,height:844},isMobile:true,hasTouch:true});const m=await ctx.newPage();watch(m);await m.addInitScript(()=>{localStorage.setItem('rex-pursuit-quality','low');localStorage.setItem('rex-pursuit-campaign-v1',JSON.stringify({version:1,ravine:true}));});await m.goto(url);await ready(m);await m.screenshot({path:`${out}/menu-phone.png`});assert.equal(await m.evaluate(()=>document.documentElement.scrollWidth>innerWidth),false);await m.locator('#start').tap();await m.waitForFunction(()=>ravine.mode==='playing');await m.evaluate(()=>{ravine.freeze=true;for(let n=0;n<700;n++)ravine.step(1/60);});await m.screenshot({path:`${out}/phone-chase.png`});
  const fire=await m.locator('#fire').boundingBox(),cdp=await ctx.newCDPSession(m);await cdp.send('Input.dispatchTouchEvent',{type:'touchStart',touchPoints:[{x:180,y:400,id:1}]});await cdp.send('Input.dispatchTouchEvent',{type:'touchStart',touchPoints:[{x:180,y:400,id:1},{x:fire.x+fire.width/2,y:fire.y+fire.height/2,id:2}]});await m.evaluate(()=>{for(let n=0;n<20;n++)ravine.step(1/60);});assert.ok(await m.evaluate(()=>ravine.round.ammo<80));await cdp.send('Input.dispatchTouchEvent',{type:'touchEnd',touchPoints:[]});await m.locator('#grenade').tap();assert.ok(await m.evaluate(()=>ravine.round.grenade>0));await m.locator('#pause').tap();assert.equal(await m.evaluate(()=>ravine.mode),'paused');await m.locator('#resume').tap();await m.setViewportSize({width:844,height:390});await m.evaluate(()=>ravine.step(.02));await m.screenshot({path:`${out}/phone-landscape.png`});assert.equal(await m.evaluate(()=>document.documentElement.scrollWidth>innerWidth),false);await ctx.close();
  // Storage denied: the authorized victory continuation still plays this visit.
  const denied=await browser.newPage();watch(denied);await denied.addInitScript(()=>{Object.defineProperty(window,'localStorage',{get(){throw Error('Storage denied');}});});await denied.goto(url+'?continue=1');await ready(denied);await denied.waitForFunction(()=>ravine.mode==='playing');await denied.close();
  assert.deepEqual(errors,[]);console.log('Ravine browser passed: fresh play-test entry; real Rex victory unlock/one-click continuation; mouse/touch combat; pause; both cameras; complete fair win and loss; restart; persistence/storage denial; independent cheats; portrait/landscape; no runtime/shader/asset errors.');
 }finally{await browser.close();}
})().catch(e=>{console.error(e);process.exit(1);});
