import {AUDIO_KEY as key,DEFAULT_ROLES as defaults,readCatalog,resolveAudioSettings} from './chase/audio-catalog.js';
let stored={},saved={labels:{},roles:{...defaults}};
try{stored=JSON.parse(localStorage.getItem(key))||{};}catch{}
const status=document.querySelector('#save-status');let catalog;
function save(){try{localStorage.setItem(key,JSON.stringify(saved));status.textContent='Saved in this browser · Restart the chase to use new calls';}catch{status.textContent='Browser storage unavailable — export to keep your names';}}
function options(){for(const role of Object.keys(defaults)){const select=document.querySelector(`#${role}`);select.replaceChildren(...catalog.clips.map(c=>{const option=document.createElement('option');option.value=c.id;option.textContent=`${String(c.id).padStart(2,'0')} · ${saved.labels[c.id]||`${c.duration.toFixed(2)}s`}`;return option;}));select.value=saved.roles[role];}}
try{catalog=await readCatalog();saved=resolveAudioSettings(catalog,stored);
 for(const clip of catalog.clips){const article=document.createElement('article');article.className='clip';const number=String(clip.id).padStart(2,'0');article.innerHTML=`<div class="clip-top"><strong>CLIP ${number}</strong><span>${clip.duration.toFixed(2)} SECONDS</span></div><input aria-label="Name clip ${number}" placeholder="Name this sound…"><audio controls preload="none" src="./audio/clip-${number}.wav"></audio><div class="clip-bottom"><span>IN ${clip.start.toFixed(2)}s → OUT ${clip.end.toFixed(2)}s</span><a href="./audio/clip-${number}.wav" download>WAV ↓</a></div>`;
  const input=article.querySelector('input');input.value=saved.labels[clip.id]||'';input.addEventListener('input',()=>{saved.labels[clip.id]=input.value;save();});input.addEventListener('change',options);const audio=article.querySelector('audio');audio.addEventListener('play',()=>document.querySelectorAll('audio').forEach(other=>{if(other!==audio)other.pause();}));document.querySelector('#clips').append(article);
 }options();for(const role of Object.keys(defaults))document.querySelector(`#${role}`).addEventListener('change',e=>{saved.roles[role]=Number(e.target.value);save();});status.textContent='34 clips ready · Names save automatically';
}catch(e){status.textContent=e.message;status.classList.add('error');}
document.querySelector('#export').onclick=()=>{if(!catalog)return;const data={...catalog,roles:saved.roles,clips:catalog.clips.map(c=>({...c,label:saved.labels[c.id]||''}))};const url=URL.createObjectURL(new Blob([JSON.stringify(data,null,2)],{type:'application/json'}));const a=document.createElement('a');a.href=url;a.download='rex-sound-catalog.json';a.click();setTimeout(()=>URL.revokeObjectURL(url),1000);};
